### PR TITLE
Data Viewer very lightweight API and Anatomist implementation

### PR DESCRIPTION
**Pull request by denisri**
1st implementation of a data viewer, using Anatomist (anasimpleviewer variant).
Other data viewers can be implemented.

### CODE REVIEW

**Comment by servoz** [comment]
I have this exception:
```
File "/home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/main_window.py", line 1065, in tab_changed
    self.data_viewer.activate_viewer(self.data_viewer.current_viewer())
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/data_viewer/data_viewer_tab.py", line 64, in activate_viewer
    '%s.%s' % (__name__.rsplit('.', 1)[0], viewer_name))
  File "/usr/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/data_viewer/anatomist/__init__.py", line 2, in <module>
    from .mia_anatomist import MiaViewer
  File "/home/econdami/.local/lib/python3.7/site-packages/populse_mia-1.3.0-py3.7.egg/populse_mia/user_interface/data_viewer/anatomist/mia_anatomist.py", line 11, in <module>
    from anatomist.simpleviewer.anasimpleviewer import AnaSimpleViewer
ModuleNotFoundError: No module named 'anatomist'

```
where can i find anatomist ?
Linux  5.5.15-200.fc31.x86_64

**Comment by servoz** [comment]
[I found this](http://brainvisa.info/web/download.html). Does that mean that in order to have anatomist we have to install the entire BrainVisa Suite?

**Comment by denisri** [comment]
This will not work for mia right now:
The installer allows to download/install the needed modules (not necessarily all of it). Checking just anatomist will install anatomist and its dependencies, but this is already a big piece, which includes a binary distribution of python. And for now, it is a python 2.7 which is not compatible with populse_mia.
For now the easiest way is to use [casa-distro](https://github.com/brainvisa/casa-distro) and use it to rebuild anatomist + python bindings using python3. We will provide VMs when possible.

**Comment by servoz** [comment]
ok thanks

**Comment by sapetnioc** [comment]
I built my first two virtual machines with all runtime and developement
dependencies. They are big enough to take several days to upload from where
I am quarantined (I will have to work on size optimization). But, I believe
I am close to test and share a complete environment that would make it
possible to play with Mia and Anatomist on any machine supporting
VirtualBox. For Linux only, we already have containers that could be used
immediately but we still have to document and test the procedure for the
distribution of a development (or runtime) environment. This is just
downloading and mounting a directory in the container (or virtual machine)
we do it daily so we know it works. But if we share such a directory over
internet, there are a few things that we must decide or check. For instance
what is the list of projects to include, how are handled files permissions
and dates on various systems (it can be important when compilation and
makefiles are involved).

**Comment by servoz** [comment]
Ok we'll play with that when it's will be available !
 I'm struggling with the unit tests during the continuous integration for mia... it's leaking all over the place ... So, I've got something to play in the meantime !

**Pull request merged**
