### PR TITLE
Get rid of Travis

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**

### CODE REVIEW

**Comment by servoz** [comment]
@DimitriPapadopoulos What was the issue with #.travis.yml?

**Comment by DimitriPapadopoulos** [comment]
Why keep it? Travis has not been working fine for a long time. Besides, it started with `#`.

**Comment by servoz** [comment]
As a rule of thumb, we use the # character at the beginning of a name to indicate that it's something we no longer use, but want to keep for now...

**Comment by servoz** [comment]
Ok, I think we can live without this file, but please keep this little rule in mind.

**Comment by DimitriPapadopoulos** [comment]
That's what git is for, isn't it?

**Comment by servoz** [comment]
We can live without it. Leave it as it is! Deleting a file is not a big job, just like finding it with git.

**Pull request merged**
