### PR TITLE
Fix scaling of images in the mini-viewer when they contain nans

### LINKED ISSUE #73: RuntimeWarning raised when handling NaN values.
ex. 
 - [/usr/local/lib64/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)
/usr/local/lib64/python3.6/site-packages/numpy/core/_methods.py:153: RuntimeWarning: invalid value encountered in reduce
  umr_maximum(a, axis, None, out, keepdims),](https://stackoverflow.com/questions/49013049/runtimewarning-invalid-value-encountered-in-reduce)
with a spm realigned scan
- [/home/econdami/Git_Projects/populse_mia/python/populse_mia/data_browser/mini_viewer.py:773: RuntimeWarning: invalid value encountered in true_divide
  / self.im_2D[idx].ptp() * 255.0)](https://stackoverflow.com/questions/14861891/runtimewarning-invalid-value-encountered-in-divide)
with c1_, c2_, c3 segmented images

It seems this is coming from running matrices with NaN or inf values.

It may be considered to 'clean' the matrices when using mini viewer ... Can be not easy to do (I do not really thought about how to do yet !)

### PR DESCRIPTION
**Pull request by JanWP**
This works for me to display images containing NaNs. The code should be faster than previously. I'm expecting this to close #73.

Signed-off-by: Jan Warnking <JanWP@users.noreply.github.com>

### CODE REVIEW

**Comment by servoz** [comment]
I just tested your branch.
1/ I'm observing this warning:
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
QPixmap::scaleHeight: Pixmap is a null pixmap
I didn't take the time to understand why I'm seeing this Warning in the terminal. Do you have any idea?
2/ For the problem observed with realign (first point of the issue #73). It is now possible to see the image, for slice 2 to 52. Not for the slice 1 and 53 ... And I observe a change in the dimension of the images 1 and 53 (smaller than the others). Again, I d'idn't take the time to understand ...
3/ For the problem observed with segment (second point of the issue #73). I do not observed the warning (populse_mia/user_interface/data_browser/mini_viewer.py:413: RuntimeWarning: invalid value encountered in true_divide
/ self.im_2D[idx].ptp() * 255.0)

So the second point of the issue #73 seems fixed. But I propose to deal with the point 1 and 2 of this comment before to merge this PR.

**Comment by JanWP** [comment]
Sounds like the first and last slices of your image are all NaNs. I have not tested that code path and will look into it.

**Comment by JanWP** [comment]
Regarding the warning, I do get it upon startup of MIA, independently of the proposed patch. I do not get this warning when viewing images. Could you maybe provide a sample image that produces this warning?

**Comment by servoz** [comment]
Sure, the warning is displayed at startup, without any image to see in the miniviewer. Unless I'm mistaken, these warning are not observed with the current master branch. If we merge this PR to the master branch we will propagate this warning. So I propose to remove this warning from your branch before to merge.

**Comment by JanWP** [comment]
I do get these warnings also with the master branch prior to merge here. The code I modified in the pull request is not executed at startup, unless I'm mistaken.

**Comment by M40V** [comment]
_QPixmap::scaleHeight: Pixmap is a null pixmap_
I've seen warning when MIA couldn't find the logo and icons used by the software. 
I currently do not observe this warning on my station even with @JanWP branch.

**Comment by M40V** [comment]
If you check the /python/populse_mia/sources_images directory, you might find that some pictures are corrupted or empty.

**Comment by servoz** [comment]
This PR is merged since 44 mins ...

**Pull request merged**
